name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Yarn Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: "install --ignore-engines --ignore-scripts"

      - name: Run Tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: "test:ci"

      - name: Code Cov
        uses: codecov/codecov-action@v2.1.0
