name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Yarn Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: "install --ignore-engines --ignore-scripts"

      - name: Run Linters
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
