name: Publish + Release on Version Bump
on: push
# on:
#   push:
#     branches:
#       - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Yarn Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: "install --ignore-engines --ignore-scripts"

      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 3.1

      - name: Build
        run: yarn build

      # - name: Run Tests
      #   run: yarn test:ci

      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          dry-run: true
          token: ${{ secrets.NPM_TOKEN }}

      - if: steps.publish.outputs.type != 'none'
        name: Generate Binary
        run: bin/pkg

      - if: steps.publish.outputs.type != 'none'
        name: Get pkg-sha
        run: echo ::set-output name=PKG_SHA::$(shasum -a 256 ./release/gnar.tar.gz | cut -d " " -f 1)
        id: pkg_sha

      - if: steps.publish.outputs.type != 'none'
        id: release
        name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          body: SHA ${{ steps.pkg_sha.outputs.PKG_SHA }}
          # tag_name: test-v${{ steps.publish.outputs.version }}
          tag_name: test-TEST
          generate_release_notes: true
          files: ./release/gnar.tar.gz

      - if: steps.publish.outputs.type != 'none'
        name: Assets Test
        run: echo "${{ steps.release.outputs.keys }}"

      - if: steps.publish.outputs.type != 'none'
        name: Prepare Template Forumla
        run: |
          sed -i'.bkp' "s/$URL/\'foo\'/" Formula/gnar.rb
          sed -i'.bkp' "s/$SHA/\'${{ steps.pkg_sha.outputs.PKG_SHA }}\'/" Formula/gnar.rb
          sed -i'.bkp' "s/$VERSION/\'${{ steps.publish.outputs.version }}\'/" Formula/gnar.rb

      - if: steps.publish.outputs.type != 'none'
        name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.GNARBOT_TOKEN }}
        with:
          source_folder: Formula
          destination_repo: TheGnarCo/homebrew-gnar
          # destination_head_branch: update-v${{ steps.publish.outputs.version }}
          destination_head_branch: update-TEST
          user_email: gnarbot@thegnar.co
          user_name: gnarbot
