name: Publish + Release on Version Bump
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Yarn Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: "install --ignore-engines --ignore-scripts"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test:ci

      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - if: steps.publish.outputs.type != 'none'
        name: Generate Binary
        run: bin/pkg

      - if: steps.publish.outputs.type != 'none'
        id: pkg_sha
        name: Get pkg-sha
        run: echo ::set-output name=PKG_SHA::$(shasum -a 256 ./release/gnar.tar.gz | cut -d " " -f 1)

      - if: steps.publish.outputs.type != 'none'
        id: release
        name: Upload Release Asset
        uses: softprops/action-gh-release@HEAD
        with:
          body: SHA ${{ steps.pkg_sha.outputs.PKG_SHA }}
          tag_name: v${{ steps.publish.outputs.version }}
          generate_release_notes: true
          files: ./release/gnar.tar.gz

      - if: steps.publish.outputs.type != 'none'
        id: asset_url
        name: Assets
        run: echo ::set-output name=ASSET_URL::${{ fromJson(steps.release.outputs.assets)[0].browser_download_url }}

      - if: steps.publish.outputs.type != 'none'
        name: Prepare Template Forumla
        run: |
          sed -i'.bkp' 's|$URL|${{ steps.asset_url.outputs.ASSET_URL }}|' Formula/gnar.rb
          sed -i'.bkp' 's/$SHA/${{ steps.pkg_sha.outputs.PKG_SHA }}/' Formula/gnar.rb
          sed -i'.bkp' 's/$VERSION/${{ steps.publish.outputs.version }}/' Formula/gnar.rb
          rm -f ./Formula/*.bkp

      - if: steps.publish.outputs.type != 'none'
        name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.GNARBOT_TOKEN }}
        with:
          source_folder: Formula
          destination_repo: TheGnarCo/homebrew-gnar
          destination_head_branch: update-v${{ steps.publish.outputs.version }}
          user_email: gnarbot@thegnar.co
          user_name: gnarbot
