on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Yarn Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: "install --ignore-engines --ignore-scripts"

      - name: Run Tests
        run: yarn test:ci

      - run: yarn build

      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          dry-run: true
          token: ${{ secrets.NPM_TOKEN }}

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

      - if: steps.publish.outputs.type != 'none'
        run: bin/pkg

      - if: steps.publish.outputs.type != 'none'
        name: Get pkg-sha
        run: echo '::set-output name=PKG_SHA::$( shasum -a 256 ./releases/gnar.tar.gz)'
        id: pkg_sha

      - if: steps.publish.outputs.type != 'none'
        id: create_release
        uses: avakar/tag-and-release@v1
        with:
          tag_name: test-v${{ steps.publish.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.publish.outputs.type != 'none'
        name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./releases/gnar.tar.gz
          asset_name: gnar.tar.tz
