on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Yarn Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: "install --ignore-engines --ignore-scripts"

      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          dry-run: true
          token: ${{ secrets.NPM_TOKEN }}

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

      - if: steps.publish.outputs.type != 'none'
        uses: avakar/tag-and-release@v1
        with:
          tag_name: test-v${{ steps.publish.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
